# -*- mode: python ; coding: utf-8 -*-
# PyInstaller 打包配置文件 - 智优进程管理器 v1.2.3 单文件版

import os
import sys

block_cipher = None

project_root = os.path.dirname(SPEC)

a = Analysis(
    ['process_priority_manager.py'],
    pathex=[project_root],
    binaries=[],
    datas=[
        ('config/app_categories.yaml', 'config'),
        ('config/scoring_rules.yaml', 'config'),
        ('config/cross_factors.yaml', 'config'),
        ('dashboard/index.html', 'dashboard'),
        ('ml/models/classifier_pipeline.pkl', 'ml/models'),
        ('ml/models/imputer.pkl', 'ml/models'),
        ('ml/models/label_encoder.pkl', 'ml/models'),
        ('ml/models/scaler.pkl', 'ml/models'),
        ('ml/models/scoring_model.pkl', 'ml/models'),
    ],
    hiddenimports=[
        'psutil',
        'yaml',
        'json',
        'threading',
        'queue',
        'concurrent.futures',
        'win32gui',
        'win32process',
        'win32api',
        'win32con',
        'win32service',
        'win32serviceutil',
        'winreg',
        'wmi',
        'pystray',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'sklearn',
        'sklearn.ensemble',
        'sklearn.preprocessing',
        'sklearn.model_selection',
        'sklearn.metrics',
        'sklearn.impute',
        'numpy',
        'core.constants',
        'core.classifier',
        'core.scorer',
        'core.singleton',
        'core.cache',
        'core.di_container',
        'core.logger',
        'core.gpu_manager',
        'core.alerting',
        'config.config_manager',
        'config.config_validator',
        'monitoring.history_manager',
        'monitoring.performance_counter',
        'monitoring.network_monitor',
        'ml.scoring_model',
        'ml.smart_classifier',
        'core.nvidia_optimizer',
        'core.gui_manager',
        'core.subprocess_utils',
        'core.thread_utils',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'pandas',
        'scipy',
        'IPython',
        'jupyter',
        'notebook',
        'unittest',
        'pytest',
        'fastapi',
        'uvicorn',
        'pydantic',
        'flask',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    name='智优进程管理器',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)