; Inno Setup Script for Smart Process Priority Manager
; Generated by Trae AI Agent

[Setup]
AppId={{0A1B2C3D-4E5F-6789-ABCD-EFGHIJKLMNOP}
AppName=智优进程管理器
AppVersion=1.2.0
AppPublisher=Smart Process Manager
AppPublisherURL=https://github.com
AppSupportURL=https://github.com
AppUpdatesURL=https://github.com
DefaultDirName={pf}\智优进程管理器
DefaultGroupName=智优进程管理器
AllowNoIcons=yes
LicenseFile=LICENSE.txt
OutputDir=installer
OutputBaseFilename=setup_智优进程管理器_v1.2.0
Compression=lzma2/ultra
SolidCompression=yes

[Languages]
Name: "chinese"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "创建桌面快捷方式"; GroupDescription: "附加任务:"; Flags: unchecked

[Files]
Source: "dist\智优进程管理器\智优进程管理器.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "dist\智优进程管理器\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "dist\智优进程管理器\config\*"; DestDir: "{app}\config"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "dist\智优进程管理器\dashboard\*"; DestDir: "{app}\dashboard"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "dist\智优进程管理器\ml\*"; DestDir: "{app}\ml"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\智优进程管理器"; Filename: "{app}\智优进程管理器.exe"; WorkingDir: "{app}"
Name: "{group}\卸载 智优进程管理器"; Filename: "{uninstallexe}"
Name: "{commondesktop}\智优进程管理器"; Filename: "{app}\智优进程管理器.exe"; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
Filename: "{app}\智优进程管理器.exe"; Description: "启动智优进程管理器"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{app}"