; NSIS Installer Script for Smart Process Priority Manager
; Generated by Trae AI Agent

!define APP_NAME "智优进程管理器"
!define APP_VERSION "1.2.0"
!define APP_PUBLISHER "Smart Process Manager"
!define APP_URL "https://github.com"
!define APP_EXE "智优进程管理器.exe"

!include "MUI.nsh"

; MUI Settings
!define MUI_ICON "icon.ico"
!define MUI_UNICON "icon.ico"
!define MUI_WELCOMEPAGE_TITLE "$(APP_NAME) v$(APP_VERSION)"
!define MUI_WELCOMEPAGE_TEXT "欢迎安装 $(APP_NAME)。$\n$\n这个工具可以智能管理进程优先级，优化游戏性能。"
!define MUI_FINISHPAGE_TEXT "安装完成！$\n$\n点击完成启动 $(APP_NAME)。"

; Pages
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "SimpChinese"

Name "$(APP_NAME)"
OutFile "setup_$(APP_NAME)_v$(APP_VERSION).exe"
InstallDir "$PROGRAMFILES\$(APP_NAME)"
InstallDirRegKey HKLM "Software\$(APP_NAME)" "InstallDir"

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  
  ; Copy main executable
  File "dist\智优进程管理器\智优进程管理器.exe"
  
  ; Copy all dependencies
  File /r "dist\智优进程管理器\_internal\*"
  File /r "dist\智优进程管理器\config\*"
  File /r "dist\智优进程管理器\dashboard\*"
  File /r "dist\智优进程管理器\ml\*"
  
  ; Create shortcuts
  CreateShortcut "$SMPROGRAMS\$(APP_NAME).lnk" "$INSTDIR\$(APP_NAME).exe"
  CreateShortcut "$DESKTOP\$(APP_NAME).lnk" "$INSTDIR\$(APP_NAME).exe"
  
  ; Add to registry
  WriteRegStr HKLM "Software\$(APP_NAME)" "InstallDir" "$INSTDIR"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\$(APP_NAME)" "DisplayName" "$(APP_NAME)"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\$(APP_NAME)" "UninstallString" "$INSTDIR\uninstall.exe"
  
SectionEnd

Section "Start Menu Shortcut" SEC02
  CreateDirectory "$SMPROGRAMS\$(APP_NAME)"
  CreateShortcut "$SMPROGRAMS\$(APP_NAME)\$(APP_NAME).lnk" "$INSTDIR\$(APP_NAME).exe"
  CreateShortcut "$SMPROGRAMS\$(APP_NAME)\Uninstall.lnk" "$INSTDIR\uninstall.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninstall.exe"
SectionEnd

Function .onInstSuccess
  MessageBox MB_OK "安装成功！$\n$\n$(APP_NAME) 已安装到:$\n$INSTDIR"
FunctionEnd